### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MysarioN** [SeaRoll/hi1031-webshop#6]
Betyg 3
**User**
- [ ] Register
- [ ] Login
- [ ] State
- [ ] Role

**Cart** 
- [ ] Titta
- [ ] lägga in
- [ ] ta bort

Betyg 4
**Item**
- [ ] Quantity
- [ ] Skicka order som transaktion
- [ ] Finnas roller

Betyg 5
**Order**
- [ ]     Send order
- [ ]     View order

**Admin - User**
- [ ]     View all users
- [ ]     Change users
- [ ]     Delete users

**Admin - Item**
- [ ]     View all items
- [ ]     Create new items
- [ ]     Change items
- [ ]     Delete items

**Admin - Order**
- [ ]     View all orders
- [ ]     Change order status
